<?php

namespace police\PoliceBundle\Repository;

/**
 * CommissariatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissariatRepository extends \Doctrine\ORM\EntityRepository
{
}
