<?php

namespace police\PoliceBundle\Repository;

/**
 * InfractionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfractionRepository extends \Doctrine\ORM\EntityRepository {
    /**
     * Permet de recuperer les attestaion inclu les infractions
     * @param type $idAttestation
     * @return type
     */
     public function InfractDunAtt($idAttestation) {
        $qb = $this->createQueryBuilder('inf')
                ->select('inf')
                ->leftJoin('inf.attestation', 'att')
                ->andWhere('att.id =:id')
                ->setParameter('id', $idAttestation);

        return $qb->getQuery()->getResult();
    }
    

}
