utilisateurs:
    resource: "@UtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

police:
    resource: "@PoliceBundle/Resources/config/routing.yml"
    prefix:   /

#app:
#    resource: '@AppBundle/Controller/'
#    type: annotation

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /admin