<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * CommissaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommissaireRepository extends \Doctrine\ORM\EntityRepository
{
}
