<?php

namespace Utilisateurs\UtilisateursBundle\Repository;

/**
 * PolicierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PolicierRepository extends \Doctrine\ORM\EntityRepository
{
}
