easy_admin:
    site_name: 'VIGIROUTE-ADMIN'
    formats:
        date:    'd/m/Y'
        time:    'H:i'
        datetime: 'd/m/Y H:i:s'
    list:
        max_results: 7
        
    entities:
        Zone:
            class: police\PoliceBundle\Entity\Zone
            label: 'Zone'
            controller: Utilisateurs\UtilisateursBundle\Controller\UserController
            
        Brigade:
            class: police\PoliceBundle\Entity\Commissariat
            label: 'Brigade'
            controller: Utilisateurs\UtilisateursBundle\Controller\UserController
            
        Commissaire:
            class: Utilisateurs\UtilisateursBundle\Entity\Commissaire
            label: 'Superviseur de la brigade'
            controller: Utilisateurs\UtilisateursBundle\Controller\UserController
            form:
                fields:
                - { property: 'nomChef' }
                - { property: 'prenomChef'}
                - { property: 'typeSuperviseur', type:'choice', type_options: {choices: {'Superviseur':'Superviseur','Superviseur General':'Superviseur General'}}}
            
        Agent:
            class: Utilisateurs\UtilisateursBundle\Entity\Policier
            label: 'Agent de la brigade'
            controller: Utilisateurs\UtilisateursBundle\Controller\UserController
            form:
                fields:
                - { property: 'nomAgent' }
                - { property: 'prenomAgent'}
                - { property: 'matriculeDuAgent'}
                - { property: 'commissariat'}
                - { property: 'typeAgent', type:'choice', type_options: {choices: {'Agent de circulation':'Agent de circulation','Agent remet piéce':'Agent remet piéce', 'Percepteur':'Percepteur'}}}
            

            
            